name: Build Flutter APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Android Build ရန် လိုအပ်သော Java ကို ထည့်သွင်းခြင်း
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - run: flutter pub get
    - run: flutter build apk --debug
    
    - uses: actions/upload-artifact@v4
      with:
        name: heybro-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
        
